### ISSUE TITLE
Files display the list from the master branch in Translation mode

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1047]
translationCore Create - v1.3.0 build 72-a6038d2

In the stepper, files shows the list from the Master branch instead of Published files list, in Translation mode(GL orgs):
![Screen Shot 2021-10-06 at 2.05.53 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/921a120b-52d2-4446-a1f1-c0a7dada3b15)

**Comment by mandolyte** [comment]
Some observations (just processing this problem):
- If the GLs need to get their file list from the latest release, then the English GL is blocked from releasing anything if any GL that needs the data in a prior format
- Hopefully, all GLs will coordinate therefore the format needed
- The Gitea React Toolkit's file management components are not currently aware of the selected organization, which means it can't decide to get a file list from a release.
- Since it doesn't know, the app is going to have to inform it. 
- Since the org is known by the time the file list is acquired, we might re-architect the file list component to take a tag or branch as an optional parameter (I think this is the same conclusion that @ancientTexts-net had come to).
- This approach would maintain GRT's independence from uW's DCS.
