### ISSUE TITLE
SPIKE: How to scroll to a location on the correct page

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1075]
We need to develop a way to position (not just filter) the file at a particular record.

Break into small issues.
Broken into:
#1088
#1089

**Comment by mandolyte** [comment]
Hey @birchamp! @Joel-C-Johnson has made some progress on studying the problem. Before we break down this spike into issues, I think we need a goal (or goals). Here are examples I thought of. Can you review and adjudicate for us? Thanks!

*We need to position the file at a particular location because*:
1. when the user uses the search, they want to position the file at one of the search results
2. when the user uses the search and then closes it, they want to return to where they were before they searched
3. the user needs to be able to bookmark one or more locations in the file and easily re-position the file at those bookmarked locations

@birchamp @ancientTexts-net

**Comment by birchamp** [comment]
1. Yes they want to be able to position the file at one of the search results.
2. This is not typical, but one solution that I can think of is:
  a. If the user clicks and places the caret inside a record then that is the result to center on.
  b. if the user doesn't click then they return to their previous location
3. I can see bookmarks being useful but it hasn't been requested yet.

**Comment by mandolyte** [comment]
@Joel-C-Johnson Looks like item 1 is the goal. And item 2 is pretty much what your were trying to do already. Here are my thoughts on a list of spike issues:

### Add Go To button to row header
This button would typically be clicked on a row in search results. When clicked:
- Search is closed (programmatically) (if open)
- The row Id (row number??) is noted (does datatable-translatable know there is a row id and which column it is in??)
- The data table is positioned is positioned at that row (top of page/viewport?)
- Possible complicating factors: 
   - how will a generic datatable uniquely identify a row?
   - does pagination interfere with how positioning works?

### Return to last edited row
If the search is closed by the user, then either:
1. If the user has unsaved changes, it will return to where the user was last working
2. Otherwise, it will return to the "page" that the user was last viewing

**Comment by birchamp** [comment]
@birchamp break down in to issues
