### ISSUE TITLE
Save jumps to top of page

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/tc-create-app#115]
When I save a change to a tN, the page resets to the top of the page. I have to scroll down to try to find where I was working, and wait for the scripture viewer to render again.

**Comment by elsylambert** [comment]
Beta-13. Save actions makes page to scroll to top.

**Comment by birchamp** [comment]
@mandolyte  check scroll to top both in tC-create-app and datatable-translatable.

**Comment by mandolyte** [comment]
@klappy  At this line: https://github.com/unfoldingWord/tc-create-app/blob/develop/src/components/translatable/Translatable.js#L66

If you comment it out, it seems to fix it... this is the line I had noticed before and mentioned during the planning meeting today.

However, the context is within a hook and the only thing it does is scroll to top (if targetFile has a value):
```
  useEffect(() => {
    if (targetFile) {
      //scrollToTop();
    }
  }, [targetFile, scrollToTop]); 
```
So I think I may be overlooking something here. Thoughts?

**Comment by klappy** [comment]
@mandolyte The useEffect in this case is being used to trigger when a new file has been selected by the user.

Since we need it to be there, but fire only when the filename has changed, you can try changing both the `targetFile` uses with `filepath`. In theory, it should only fire when the `filepath` changes and should give us the result we are looking for.

**Comment by mandolyte** [comment]
Looks like that works... new hook looks like this:
```
  useEffect(() => {
      scrollToTop();
  }, [filepath, scrollToTop]); 
```
I think because object `targetFile` has the content, it changes every time I update the target text. So just leaving it out seems to do what's needed.

Is there somewhere else in this app where it scrolls to the top that I need to look at?

If not, I'll clean up my code and submit the PR

@klappy

**Comment by klappy** [comment]
@mandolyte Nice and clean. This is the only new issue that I am aware of.

**Comment by klappy** [comment]
Do you have a PR ready for this one yet?

**Comment by elsylambert** [comment]
Looks good in Beta-14. Save action does not scroll to top.
