### ISSUE TITLE
Manage versions in the Parallel scripture viewer is broken

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1191]
1. Open tN> select file>
2. Check to see if the parallel scripture viewer is expanded. Toggle, if not expanded.
3. Move to a row, click on the Manage versions button in the row header.
4. Add a resource by pasting a resource link.eg. Door43-Catalog/hi/ulb/master/. Check if the resource shows up in the scripture viewer. 
5. Check/ uncheck the resource in the list and check if they show/hide.

**Comment by larrysallee** [comment]
I have been unable to add a resource. I have copied the BSB to my organization to align NT books. Files are located at https://git.door43.org/Worldview/en_bsb. I have tried to enter:

- https://git.door43.org/Worldview/en_bsb (page URL)
- https://git.door43.org/Worldview/en_bsb.git (page HTTPS)
- git@git.door43.org:Worldview/en_bsb.git (page SSH)
- git@git.door43.org:Worldview/en_bsb.git

Most of these load an older version of the ULT for reasons I can't understand. The SSH link gives an "Error Undefined" message with UGNT text.

Have I not been able to stumble on the correct code, or is this broken??

**Comment by elsylambert** [comment]
@RevantCI Please see the above comment: In manage versions for parallel scripture, when above link https://git.door43.org/Worldview/en_bsb  is used to add the resource, it is adding ULT old version and not the one entered. Please look into this issue.

**Comment by larrysallee** [comment]
FWIW, I looked at my BSB repo some more, and see that when I try to do a Preview from https://git.door43.org/Worldview/en_bsb, it opens the ULT. However, clicking "See on DCS" from the Preview page takes me back to my Worldview/BSB repo.

I suspect the fact that I temporarily copied the License, Manifest, and Media files from the ULT might be confusing the tools. I didn't take time to update them because 1) I'm not sure I know how, and 2) I didn't think it mattered yet as this is a private text project. **_If_** that is what is causing the problem, I would appreciate knowing which of those files is the issue so I can mess with as little as possible and not break something else.

**Comment by larrysallee** [comment]
OK, I think I figured it out. tC-Create does indeed open the BSB from the link in the OP. However, the _**label**_ on the text shows the ULT instead of the BSB. The text itself is correct. So, I'll assume it is a problem with one of those background pages and work on fixing them.

Sorry for the confusion.

**Comment by larrysallee** [comment]
Updated front matter. All good now, it appears.

![image](https://github.com/unfoldingWord/tc-create-app/assets/143423897/167bc9a1-882d-49c9-94db-ca46ce0e876f)

**Comment by elsylambert** [comment]
@richmahn Can you please answer Larry's question?

**Comment by larrysallee** [comment]
@elsylambert @richmahn I got it. Works now. Problem was in the front matter. Thanks for your help.

**Comment by elsylambert** [comment]
Glad that it works!!! Thanks.

**Comment by larrysallee** [comment]
@elsylambert More important, the highlighting works in the BSB after I test aligned 3John! That was the point of the whole test.
