### ISSUE TITLE
Scripture pane collapsed by default

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#129]
Due to both performance #116 and screen clutter, it may be preferable to have the scripture pane collapsed by default.

**Comment by birchamp** [comment]
DoD: The user can have unrendered/collapsed scripture panes by default

**Comment by birchamp** [comment]
@RoyalSix  add a toggle arrow MUI button rendered to the left of the text to toggle the view

**Comment by klappy** [comment]
Testable in `1.0.0-beta.2`

**Comment by ancientTexts-net** [comment]
After I merged scripture-resources-rcl v1.0.0-rc.4 into my feature branch, I'm seeing a strange bug.  As far as I can tell, this bug is in v1.0.0-rc.4.
Can you please help me see what's going on?

At this point, I'm hesitant to request the PR for feature #148: Add resource text to parallel scripture pane.  I recommend I can do my PR after we figure out if the issue below is a bug or not?

@klappy, @elsylambert, @RoyalSix, @mandolyte, can you please help me see what's going on?


1. Open scripture-resources RCL demo for `ParallelScripture`:
https://scripture-resources-rcl.netlify.app/#/Parallel%20Scripture%20?id=parallelscripture

`ScriptureResourcesRcl v1.0.0-rc.4`

2. Click new `Expand Scripture Pane` menu button.

3. Hide resources:
Click `View Versions` menu button.
Uncheck ULT; Uncheck UST.

Notice: The column *headers* disappear, but the resource text is still displayed.
Expected result: The corresponding text & columns should hide/show together.

4. Close/Expand Scripture pane:
Toggle the `Close Scripture Pane` / `Expand Scripture Pane` until the resource text is visible again.

Notice: The appropriate column headers/text match.

5. Show resources:
Click the `View Versions` menu button again.
Enable both ULT, UST.

Notice: The column headers are visible, but the resource text is not displayed.
Expected result: The corresponding text & columns should hide/show together.

.

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/35f149eb-02d5-4a50-889f-74e7796fa535)

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/9838b194-ffcb-4863-b20d-4f83a2f725c1)

**Comment by elsylambert** [comment]
@ancientTexts-net I have moved this issue in #157 and moved to QA Fail lane. Thanks for flagging that.

**Comment by klappy** [comment]
For some reason the memoization of objects is still problematic even though we are using the function from use-deep-compare-effect. I'm guessing that it has something to do with the following issue:

https://github.com/kentcdodds/use-deep-compare-effect/issues/13
