### ISSUE TITLE
Remove nested theme in quote selector

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#130]
This is tech debt that needs to be removed. This has the potential to help performance.

**Comment by birchamp** [comment]
per @RoyalSix Could be tested using Cypress or Chrome API

**Comment by klappy** [comment]
Upon further inspection... The nested theme is used to style the embedded table of the Parallel Scripture Viewer separately from the DatatableTranslable's MUI-datatable. There is another approach to doing this but will require much more effort.

When removing it, it formatted the verses vertically (like the note's row data) instead of horizontally as it currently is.

@birchamp ^^
