### ISSUE TITLE
Bug: blank OccurenceNote and OrigQuote fields insert a space

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1354]
The content team has found a bug in the latest tCC release. When creating a new note, the new version includes a space in the empty OccurrenceNote and OrigQuote boxes. Unless the editor happens to catch and delete or overwrite this invisible space, it remains and causes validation errors and invalid snippets.

DoD:
---
Blank OccurrenceNote and OrigQuote fields are truly blank.

**Comment by superdav42** [comment]
I tried and can't reproduce this problem. A nbsp is added when editing a blank piece of content bit it is stripped out if it is all that exists when saving. Probably there's a case when it's not stripped but I can't get it to happen. Can you provide more detailed instructions to reproduce the issue?

**Comment by mandolyte** [comment]
@superdav42 did you also check for u200B? As I recall the "zero width space" was preferred for solving the issue with rendering empty components. 

Note: we inserted that to solve an issue with a text component not rendering properly when there was no content. It would be nice if that was no longer a problem, since this solution is clearly work-around and bit of a kludge.

In theory, the character should only have been inserted when no content. Then all such characters should be stripped on save.

If it is causing validation errors prior to saving (on-demand validation), then perhaps we overlooked stripping the character prior to providing to the uw-content-validation module.

**Comment by elsylambert** [comment]
"Unexpected non-break space (u00A0) character"
To replicate:
- Open tN and a new row with no data in Occurrence Notes. Add some text and save the file
- Run Content validator from the header menu. Note that the "Unexpected non-break space (u00A0) character" shows for the newly added row.

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.6.0 build 161-1f4e570.
