### ISSUE TITLE
EPIC: Add merging functionality

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1566]
#1545 is a spike that informs this epic.

**Pulling from master:**

![CleanShot 2023-04-11 at 16.26.34@2x.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/41445d8a-18df-4c3b-88f0-849eb7cc9e81)

**Pushing to Master:**

![CleanShot 2023-04-11 at 15.15.17@2x.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/3a656ac6-bb36-4477-9cf7-9aeeec48a43e)

**Prompting for comment:**
![CleanShot 2023-04-13 at 10.08.58.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/3a1696c3-8c9c-447f-a80d-ee3c519a3888)

**Comment by birchamp** [comment]
@Joel-C-Johnson @abelpz 
Here are the mockups for merging.  You'll need to find out if on "merge my work" whether you need to do: pull, save, and push to Master.

**Comment by abelpz** [comment]
Thanks  @birchamp  we'll look into it.

**Comment by jincypjose** [comment]
Thanks @birchamp we will take a look for gateway-edit

**Comment by birchamp** [comment]
@mandolyte @abelpz Did we figure out if prior to pushing whether we need to do a pull from master first?

**Comment by mandolyte** [comment]
It isn't necessary. The merge functions will create the PR of it doesn't
exist.

The only reason to update before merging is to see what changes have been
committed since your branch was started.

Branches named without book id will bring in latest of all the other files
and it can update the file you are working on too. But only in your branch.
The app must refresh its local in memory copy. This is an app specific
retirement. The merger package can't help. This is what led to issue 5 in
the merger package, to help determine if the file you are working on has
changed when the user branch was updated.

How that helps
