### ISSUE TITLE
opening a file without write permissions results in a infinite spinner

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#244]
If the user doesn't have write permissions for the file no error is given. 

An error should inform the user that they need write permissions.

**Comment by mandolyte** [comment]
@birchamp based on your description, they never get to the point of seeing, much less editing, of the file.

Correct?

I'll try to replicate the problem in tc-create itself to be sure...

**Comment by birchamp** [comment]
@mandolyte correct.  It just spins.  I don't know that they weren't members.  I think they were members of a more restricted team.

**Comment by mandolyte** [comment]
@RoyalSix @birchamp 
Jay -- Birch suggested that I look at fixing this at the org picker level. Two ways:
1. If they pick an org for which they only have read access show an error.
2. Filter the orgs for which they are member and only show those for which they have write access.

On option 1: This method would be easier for the user since the error could point them to their admin to fix it.
On option 2: This method might be easier to implement since the org component is probably already filtering to show only orgs they have access to. So this could be implemented by further filtering at the same code location.

For posterity, here are the APIs that could be used:

**This API shows the teams of an org:**
It shows two teams: the owners team (with owner [all] permissions) and a "read_test" team with only "read" permissions.

Request URL: https://git.door43.org/api/v1/orgs/translate_test/teams?access_token=PlaygroundTesting

Results:
```json
[
  {
    "id": 159,
    "name": "Owners",
    "description": "",
    "organization": null,
    "permission": "owner",
    "units": [
      "repo.code",
      "repo.issues",
      "repo.pulls",
      "repo.releases",
      "repo.wiki",
      "repo.ext_wiki",
      "repo.ext_issues"
    ]
  },
  {
    "id": 172,
    "name": "read_test",
    "description": "this is a read access only team",
    "organization": null,
    "permission": "read",
    "units": [
      "repo.code",
      "repo.issues",
      "repo.pulls",
      "repo.releases",
      "repo.wiki",
      "repo.ext_wiki",
      "repo.ext_issues"
    ]
  }
]
```

**This API tests my membership in a team**
Test each team to see if I'm in it or not.

Request URL: https://git.door43.org/api/v1/teams/159/members/cecil.new?access_token=PlaygroundTesting

id '159' yields error "must be a member":
```json
{
  "message": "Must be a team member",
  "url": "https://git.door43.org/api/swagger"
}
```

Request URL: https://git.door43.org/api/v1/teams/172/members/cecil.new?access_token=PlaygroundTesting

id '172' yields:
```json
{
  "id": 0,
  "login": "cecil.new",
  "full_name": "",
  "email": "cecil.new@noreply.door43.org",
  "avatar_url": "https://git.door43.org/avatars/f8a86db8b875c63428a3d89dae47cf84",
  "language": "",
  "is_admin": false,
  "last_login": "0001-01-01T00:00:00Z",
  "created": "2019-09-19T13:37:42Z",
  "username": "cecil.new"
}
```

Thus I only have read access and that is not sufficient to use tC Create.

**Comment by mandolyte** [comment]
@birchamp @BincyJ @RoyalSix @ancientTexts-net 
Here is what I have so far. Using the above process, the app knows if you have write access to the org or not (i.e., whether you belong to a *team* that has write access). Now when you click on one of these, an alert is shown and you have to pick another one instead.

How does this look?

![image](https://user-images.githubusercontent.com/1289437/88673083-316be000-d0b6-11ea-96b9-60296281afa4.png)

**Comment by RoyalSix** [comment]
@mandolyte  Nice so it looks like you went with option 1!

@birchamp how is the alert message?

**Comment by mandolyte** [comment]
@RoyalSix -- yeah, went with option 1... as it turns out I doubt it was much more effort and hopefully make the translation teams self-supporting.

**Comment by birchamp** [comment]
@mandolyte I like option 1.  The error message should read like the other errors that we have when the user has no org or no repo.

**Comment by mandolyte** [comment]
@birchamp Do you mean the wording of the message? Which is "Write Permissions are Required! Contact the organization Admin". Or do you mean you don't like the use of the alert popup?

The current messages are:
```
    primaryError = 'No Organizations',
    secondaryError = 'You are not currently a member of any organizations.',
```

**Comment by birchamp** [comment]
@mandolyte Both the text and the look.  We should have a consistent look for messages.  The one I was thinking of is:
![image](https://user-images.githubusercontent.com/10272744/88678864-e43f3c80-d0bc-11ea-8001-f5f47fca7c96.png)

**Comment by birchamp** [comment]
@mandolyte  So for this error, let's say: 
"Your door43 user account doesn't have permission to edit the files in the organization you have chosen.  Please contact your organization administrator and request write permissions."

**Comment by mandolyte** [comment]
Found that message and is the same technique I used. So there must be some styling that makes it look different.

@RoyalSix or @ancientTexts-net Do you guys know how to style the browser alert box? Compare mine which is "white letters on black background" with the one right above that @birchamp supplied.


```
              alert(
                `The organization "${owner}" does not contain the selected translation ${language.languageName} for the repository "${description}"\nPlease make sure that your repository has been set up correctly by your organization administrator.`
              );
```

**Comment by mandolyte** [comment]
Changed wording per above. I think the alert styling is owned by the browser, not the app. So I think it will resemble the example above when used by someone else (note: I use a Chrome dark theme).
![image](https://user-images.githubusercontent.com/1289437/88716028-6abf4280-d0ec-11ea-8b39-c9b7424ee50a.png)

**Comment by ancientTexts-net** [comment]
@mandolyte can we please discuss to review API calls?
Notes in reviewable

Looks great but have a question.  Thank you!

**Comment by cckozie** [comment]
I suggest that is should be "...organization's administrator..." (possessive)
