### ISSUE TITLE
Highlighting Relationship Unclear

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/tc-create-app#25]
As a user, I want to know where the highlighting in the Scripture pane comes from so that I can know when it needs modified.

As a user I want the highlighting to come from the target's OrigQuote field so that I can see my changes.

I can't figure out if the highlights come from the OrigQuote field in the *source* or *target* when editing a TSV file.  Changing the target seems to remove all highlighting.

**Comment by mandolyte** [comment]
@jag3773 It does indeed come from the target; but there are a number of things that you have to "know":
- if you paste into target's OrigQuote field, then you *must* paste without formatting (on Windows this is Ctrl-Shift-V); in Chrome, right click, "paste as plain text".
- if you enter by hand, don't.

At any rate, I have not been able to replicate what you describe if I follow the above. If you can still replicate it following above, could you provide more detail so that I can also?

**Comment by jag3773** [comment]
Seems to be fixed now in v1.0.0-beta.5
