### ISSUE TITLE
TNs are saved to the wrong record.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#250]
see: https://unfoldingword.zulipchat.com/#narrow/stream/207526-wg-tools/topic/tC.20Create.201.2E0.20Beta.205/near/204938672

**Comment by ancientTexts-net** [comment]
I reproduced the issue by duplicating the `ID` field.
Joel did NOT copy/paste the `ID` field.  So we are still looking for a way that this field gets duplicated.

1. Create 2 new notes.
2. Copy the ID field so that both new notes have the same `ID` value.
3. Fill in the `OrigQuote` / `OccurrenceNote` fields in both notes.
4. Save.
5. Compare branch: See: the ID field is duplicated. See: the note from the 2nd record was saved into the `st record.
6. Refresh: See: Only 1 of the 2 new notes shows in tC Create.

**Comment by ancientTexts-net** [comment]
UPDATE: I was able to reproduce this in Titus by adding several new notes at a time.

**Comment by ancientTexts-net** [comment]
1. open uW English tN
2. Create 4 new notes
3. Save
4. Compare branch: See the ID field is duplicated.

**Comment by ancientTexts-net** [comment]
Confirmed in tc-create-app 1.0.1

QA PASS

**Comment by ancientTexts-net** [comment]
Turns out here was the real way to reproduce the problem:

1. login & open any TN resource
2. Add several new notes, each time copying the same original note
(click `Add a Row` several times on the same original note)
3. Save
4. Refresh to reload the resource

at this point, notice:

- only 1 of the new notes are visible (yet all exist in the file)

compare branch to see:

- duplicate `ID` field in the new rows.
- content entered in the new rows is inconsistently saved in the wrong NEW row
