### ISSUE TITLE
Enable Save button to be always 'ON'

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#319]
Currently the Save button is greyed out at times, user has to step out of the edit block to save the button. 
Expected behaviour: User should be able to save while editing without having to step out of the edit block.

**Comment by mandolyte** [comment]
Just a note... I don't think the UI component tells the app what the update to the text field is until the user clicks/tabs out. That action is called an "on-blur" event. The update to the data doesn't happen until the on-blur event triggers it.

As a consequence, if the user was able to click save prior to the on-blur the app would save the prior content of the text field instead of what the user is in the process of typing.
