### ISSUE TITLE
The popup alerts are not discoverable by the developer tools

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#350]
v1.0.3
The popups ( for permissions and file doesn't exits, there may be more) are "hidden" from the developer tools and automation tools that need some sort of identifier (Xpath or otherwise) to find the elements. This is the case in both Chrome and Firefox.

@elsylambert can show how this fails.

DoD:
---
Browser popups can be identified by developer and QA tools.

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/9facfb3f-82d7-4005-b121-ad656df65a84)

**Comment by ancientTexts-net** [comment]
looks like window.confirm is "troublesome" for other testing tools too &^^

**Comment by ancientTexts-net** [comment]
does alert() work with Katalon ?

**Comment by ancientTexts-net** [comment]
oops I meant input()

**Comment by ancientTexts-net** [comment]
https://docs.katalon.com/katalon-studio/docs/handle_alerts.html#handle-accept-alert

does this help explain anything?
Katalon & browser alerts

**Comment by mannycolon** [comment]
@elsylambert @ancientTexts-net 

Hey guys, during my pair programming session with @jincypjose and @Joel-C-Johnson I found a way to test confirm popups with Katalon. Hopefully, this is enough to fulfill this issue. 

https://www.youtube.com/watch?v=yFgwibcmylg

https://docs.katalon.com/katalon-studio/videos/handling_javascript_prompt.html

**Comment by mannycolon** [comment]
# Custom Confirm Dialog Implementation

In our pair programming session, I created a custom dialog with react and customs hooks to replace the window confirm implementation used when navigating away from unsaved changes within the app. Unfortunately, we could not do the same when closing the tab/window/page. It uses the browser APIs for this which we cannot customize. In doing this I had to change the Gitea-react-toolkit to accommodate for the changes, which meant bumping it to version 2.0.0 because of breaking changes. 
 
See PRs:
https://github.com/unfoldingWord/gitea-react-toolkit/pull/113/files
https://github.com/unfoldingWord/tc-create-app/pull/1105/files

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.4 build 107-3808f59. Katalon is able to find the elements in the new modal.![Screen Shot 2021-12-21 at 9.36.01 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/65e00aa8-2a4e-4895-8d97-dfa52744455b)
