### ISSUE TITLE
SPIKE[4]:Add TQ to the choice of resource

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#360]
Determine what's needed to add TranslationQuestions as a source text for translation in tC Create.   Does it make sense to add it as is?

**Comment by mandolyte** [comment]
@RoyalSix Shouldn't this be blocked by the effort to convert to TSV?

Here is an example of what it will be like then:
https://git.door43.org/unfoldingWord/en_translation-annotations/src/branch/master/tit/tit_tq.tsv

**Comment by RoyalSix** [comment]
@mandolyte Thanks for dropping this link for me.

<img width="749" alt="Screen Shot 2020-09-24 at 10 19 00 AM" src="https://user-images.githubusercontent.com/16184018/94178062-6fd01200-fe4f-11ea-882e-6d0d5b40883c.png">

It looks like it works in datatable translatable we will just need to provide the chapter/verse columns instead of combining them.
 i.e.
`Reference	ID	Tags	SupportReference	Quote	Occurrence	Annotation
1:1	dbtj					What was Paul's purpose in his service to God?<br>His purpose was to establish the faith of God's chosen people and to establish the knowledge of the truth.`
Should be
`Book	Chapter	Verse	ID	Tags	SupportReference	Quote	Occurrence	Annotation
TIT	1	1	dbtj					What was Paul's purpose in his service to God?<br>His purpose was to establish the faith of God's chosen people and to establish the knowledge of the truth.`

https://5f6cd67631b9c90e5fd50367--datatable-translatable.netlify.app/

**Comment by birchamp** [comment]
@RoyalSix can you do a test of the current markdown TQs? https://git.door43.org/unfoldingWord/en_tq

**Comment by RoyalSix** [comment]
@birchamp https://5f6e328e9fcc720ffb733dd4--tc-create-app.netlify.app
