### ISSUE TITLE
Spike[40]: DCS Workflow - Identify required APIs

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#452]
Explore the Gitea React Toolkit functions for the DCS workflow outlined. List all APIs interaction. Identify the existing and new ones needed.
Determine how to integrate all APIs.

Need: 
Spidel's diagram
Map it to the API calls
See what's in/not in GRT

https://docs.google.com/document/d/1VCofTKOxQXZIjrXhYlsztlHPD6fCKDbOHQeCv61JWqg/edit

**Comment by richmahn** [comment]
A active listing of CURL commands needed to for creating repos, adding/updating files, and creating PRs is in:

https://repl.it/@richmahn/dcs-api-resolve-conflicts#setup.js

and 

https://repl.it/@richmahn/dcs-api-resolve-conflicts#resolve.js

Where the former creates a PR with merging master into the the user branch, and the later, if no conflicts, merges that PR, otherwise handles conflicts and makes a new branch based on master with the user changes and conflict resolutions they choose.

**Comment by richmahn** [comment]
API calls not implemented by GRT but are API endpoints in Gitea:

- [ ] All PR CRUD API endpoints (https://git.door43.org/api/swagger#/repository/repoListPullRequests)
