### ISSUE TITLE
Create a Bible Reference Navigation RCL for use in tc-create 2.0, etc.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/tc-create-app#485]
initial design spec are in https://docs.google.com/document/d/1dEYW59IGqiU2S94G7DJYdOiglIQzxqL00l_g2lLqC7c/edit?ts=5f99d09c# :

**Bible Reference RCL**

- Testament/Book/Chapter/Verse navigation
- Previous and next for Book/Chapter/Verse
- Drop-down selection for each
- Typeable
- UI and headless UI library (https://react-table.tanstack.com/docs/overview#what-is-a-headless-ui-library)
- May also have support for owner/repo/language.
- Challenges: Verse ranges and alternate versifications.

**Comment by mvahowe** [comment]
If the USFM has \v1-2, and the UI is on "verse 1", what does "next verse" do? I can't see a safe answer to this question since, basically, the UI would be misleading the user. If "next" is v3, where is v2? If "next" is v2, with identical content to v1, doesn't that look like a bug? If \v1-2 is displayed as "verse 1", why wouldn't the user delete the part of the translation that is not in v1?

**Comment by PhotoNomad0** [comment]
Issue moved to [unfoldingWord/bible-reference-rcl #1](https://github.com/unfoldingWord/bible-reference-rcl/issues/1) via [**ZenHub**](https://www.zenhub.com/)
