### ISSUE TITLE
The validator reports wrong number of tabs on lines that don't exist in the target file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#584]
Deleted rows shouldn't produce errors. If deleted rows *must* produce errors, it should be a very low priority error, and the description should include: "This row may have been deleted intentionally."

---------------
v1.1.0 (develop)
The file is at: https://qa.door43.org/translate_test/en_tn/_edit/tc01-tc-create-1/en_tn_55-1TI.tsv

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/df12cdc3-82f7-4c4c-a2c0-1daf8dba5dad)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5904b930-ab9b-4b6f-bac5-68105af0f5af)

**Comment by mandolyte** [comment]
@cckozie The target file is shorter than the source... I didn't expect that. But easy to fix. I sent a message to @ancientTexts-net about the fix. All the other permutations (target has extra rows, target is missing rows within) are already covered.

It may be of general interest for everyone to know that the "in memory" representation of the data is a combination of both source and target, aligned on the ID column. The data is a 2D array. Each cell in the 2D array actually contains a value for both source and target. The values are delimited by a tab. The values must be split out and the first value is sent to the source side and second value to the target side.

When the data is prepared for content validation, it is looped thru and each cell split and the target side taken. 

In this bug, the target didn't have any value but it still sent an empty row, one for each row in the source.

The fix was to check whether the target row was empty and to skip it.

**Comment by cckozie** [comment]
I changed the title to clarify that wrong number of tabs is reported when the lines don't exist in the target file.
In the project cited, there are more rows in the source file than the target. For each of this "missing" rows, the validator reports "Wrong number of tabbed fields (expected 9)". I suppose that is technically correct, but probably confusing to the user. I think reporting it as missing rows would be better.

**Comment by birchamp** [comment]
@ancientTexts-net, @RobH123, @cckozie This needs to be fixed prior to release.  We've told users that high priority errors will most likely break tC, so they are going to work to hunt these down. Training has taught GLs to delete notes that don't apply to them, so teams are already deleting rows in their notes.

**Comment by cckozie** [comment]
I am failing this based on Birch's comment above, but we need clarification on what "fixed" means, both for the CV as well as the tCC app.
Should the CV not report errors where target rows are missing?
Does tCC need to show the parallel scripture and book, chapter, verse for those rows?
Are there other requirements?

**Comment by mandolyte** [comment]
The PR for this was merged into master a couple of weeks ago. And it fixes the problem reported on in this issue (more rows in source than in target).

Deleted rows, per se, should not be a problem... is it?

So yeah, needs definition... not sure what needs to be done.

**Comment by birchamp** [comment]
@mandolyte @cckozie  Deleted rows shouldn't produce errors. If deleted rows *must* produce errors, it should be a very low priority error, and the description should say: "This row may have been deleted intentionally."

**Comment by mandolyte** [comment]
And with the PR for this, no errors will be reported for fewer rows in
target than source (ie, deleted rows).

If you find otherwise, let me know.


Cecil

**Comment by cckozie** [comment]
My bad on the 988 error. It looks like the CV no longer reports this error as of 1/22/21. It looks like I tested it when it showed up in QA prior to that and it was still broken.
Looks good now in v1.1.0-rc.4 build 19-6e50a4c

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.4 build 20-936fafa. CV no longer reports wrong number of tabs error when one row is removed from the target file, as expected.
