### ISSUE TITLE
Validation errors 450 and 950 seem to be in conflict with each other. Every tA link will generate one of those two errors.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#630]
v1.1.0-rc.3

If a tA link is formatted as [[rc://en/ta/man/translate/figs-abstractnouns]], the validator reports a 450 error with the Message of "tC cannot yet process '*' language code"

When that link is "fixed" to be formatted as [[rc://*/ta/man/translate/figs-abstractnouns]], the validator reports a 950 error with the Message of "Resource container link should have '*' language code"

Thus, the operator is unable to fully resolve those errors

**Comment by birchamp** [comment]
@RobH123 any insight on this?

**Comment by RobH123** [comment]
The CV package had a bug whereby the disabling of notices for the entry point used by tC-Create wasn't working properly. (The disabling code itself was working properly in the [demos](https://unfoldingword.github.io/uw-content-validation/#/Book%20Package%20Checker%20Demo?id=bookpackagecheck).) I'm hoping this is fixed in v1.0.1 of the package but don't have confirmation of that yet.

FYI, the apparent wasteful effort of generating notices and then disabling them again is representative of internal conflict where the content team ideally want a specific format, but our existing software can't handle that. It's sometimes hard to know what should/should-not be checked. I feel it's good to keep being reminded of deficiencies that could be remedied, but I know that not everyone will agree with that way of thinking.

Anyway, the long and short of it is: the language codes have to remain in the files at present or tC will crash (I believe). However, leaving them in there, means that GL translators will have to do the extra step of globally replacing `en` with their language code in each file.

**Comment by elsylambert** [comment]
written up #637.

**Comment by cckozie** [comment]
v1.1.0-rc.4 build 19-6e50a4c
The content validator is no longer reporting 450 errors. 
It does still report 950 errors.

**Comment by elsylambert** [comment]
v1.1.0-rc.4 build 19-6e50a4c.

The reported issue no longer exists.
