### ISSUE TITLE
Add OBS Study Notes

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#660]
Add OBS Study Notes Support

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.4 build 19-6e50a4c. Study Notes for OBS looks good. Not seeing any critical issues.

**Comment by cckozie** [comment]
v1.1.0-rc.4 build 19-6e50a4c
There is a problem with the links in obs-sn. I'm writing this up here since there is not any requirements spelled out for this issue. I suspect the problem may be in the content, but being sent back to the login page after clicking on the "Back to our site" or the browser back button does not seem very user friendly.

When clicking on a link in the source side of obs-sn, this message is displayed:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/8536949e-17e8-45bb-8ea0-d0f3c5030629)
The same link in the target side looks like a link, but is not clickable.
![Screen Shot 2021-02-01 at 10.23.22 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/14738184-2deb-4318-afe5-7340f18fcd9b)

![Screen Shot 2021-02-01 at 10.23.31 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c0112fde-65f5-4714-b6f3-36e0112130fa)

**Comment by cckozie** [comment]
v1.1.0-rc.4 build 19-6e50a4c
There really aren't any requirements defined in this issue, but I'm seeing inconsistencies between this type of project and others. I suspect these may be content problems. @birchamp - Do we care about these differences at this time?

1. The naming of the resource is inconsistent with all other resource types
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/21a75707-878f-4d08-8f7b-d2abbb211667)

2. The font for the headers is significantly larger than that used in tA
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d34e0790-f762-42b4-9140-d1df82d721c9)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/11dec96c-50ed-498b-92da-1f198e413022)

**Comment by birchamp** [comment]
@cckozie I don't know why the titles are so inconsistent but the users are much more concerned with having access.  We can ask at the Sprint Review if this needs to change.   I do think that the literacy levels of the typical OBS reader vary more than the TA reader, so perhaps that's the difference in font size??

**Comment by cckozie** [comment]
I pinged the content team to fix the resource name.
I created issue #682 to address the font sizing problem.
Otherwise it looks good in v1.1.0-rc.4 build 19-6e50a4c
