### ISSUE TITLE
Book reference links do not work correctly

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#679]
The links on both the target and source side should look like links but should not be clickable. 

**DoD:** Clicking a link on either side does nothing.

--------------
v1.1.0-rc.4 build 19-6e50a4c (Moved here from #660)
There is a problem with book reference links. I don't know what the cause of the not found error is, but being sent back to the login page after clicking on the "Back to our site" or the browser back button does not seem very user friendly. 

When clicking on a book reference link in the source side (I've seen this in tn and obs-sn) this message is displayed:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/8536949e-17e8-45bb-8ea0-d0f3c5030629)
The same link in the target side looks like a link, but is not clickable.
![Screen Shot 2021-02-01 at 10.23.22 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/14738184-2deb-4318-afe5-7340f18fcd9b)

![Screen Shot 2021-02-01 at 10.23.31 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c0112fde-65f5-4714-b6f3-36e0112130fa)

**Comment by mandolyte** [comment]
## Replicate Issue
1. run: https://develop--tc-create-app.netlify.app/
2. login as tcc001 and get to obs-sn resource and select: `content/01/01.md`
3. scroll down to the heading "God's Spirit".
4. there find a couple of obs references (24:08) and (42.10).
5. these two have (invalid) URLs:
	1. https://develop--tc-create-app.netlify.app/24/08
	2. https://develop--tc-create-app.netlify.app/42/10

The raw markdown is:
```md
# God’s Spirit
This is the Holy Spirit (See: [24:08](24/08), [42:10](42/10)).
```

When one of these is clicked you get Netlify's 404 error page. Then if you click to return to the web site, you are returned to the login page. **NOTE! this is restarting tc-create from scratch.**

*However, if click the "keep me logged in" toggle, then you will be returned to where you left off.*

Since this link is to a completely different file in this resource, in order for the link to work, tc-create would have to support routing. And if you had not saved your work, it would be lost.

The link needed would have to look like one of the two methods below:

The query parameter method:
`https://develop--tc-create-app.netlify.app?org=translate_test&resource=obs_sn&language=en&file=content/24/08/08.md`

The URL method:
`https://develop--tc-create-app.netlify.app/translate_test/en_obs_sn/content/24/08/08.md`

AFAIK, tc-create does not support any kind of internal routing.

**Comment by ancientTexts-net** [comment]
FYI this issue already exists for other resources (e.g., old **tA** resources)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/b793482d-7c3b-4635-ad4d-4334cc9db647)

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0-rc.2 build 28-4717783. Links appears like links but are not clickable, works as per the Dod.

**Comment by cckozie** [comment]
Clicking links do nothing in v1.2.0-rc.2 build 28-4717783
Added tests for this to tCC tA Test Block Quotes and Sections
