### ISSUE TITLE
The validator reports errors on scripture reference links that are correctly formatted

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#707]
v1.1.0

csv file at: [https://app.zenhub.com/files/191973535/e98f630a-5ebf-4ae6-853c-9329e1c83918/download](https://app.zenhub.com/files/191973535/e98f630a-5ebf-4ae6-853c-9329e1c83918/download)

The validator reports this error, but the link works correctly in tC. 

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a76bb8b7-bd78-4e84-92ed-fc6d8624a59d)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/869b4bf2-757f-4006-8039-bc1b62cc9cf7)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4db5703b-205e-4fa3-b62e-497dadc35b09)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/7a15367f-eb36-48f2-be25-c104d146a557)

**Comment by birchamp** [comment]
@RobH123 @mandolyte is this still the case?

**Comment by RobH123** [comment]
Having a space between the two parts of a markdown link is indeed an error, even if tC automagically compensates for it. (Certainly Zulip and some other markdown processors don't handle it as a valid link. So now I'm curious if tC uses a markdown library that happens to handle it, or if tC added special code to handle bad data?)

**Comment by birchamp** [comment]
@cckozie do you know the answer above? 
@RobH123 I assume this error is so high because it could break tools. Is that correct?

**Comment by cckozie** [comment]
@birchamp 
If the question was referring to whether or not tC Create still reports that error, the answer is yes, it still reports that error.
If the question was about what libraries tC uses, then the answer is no, I don't know.

**Comment by RobH123** [comment]
@birchamp Yes, it looks like someone meant to enter a markdown link and mistakenly put a space between the two parts. So that's not normally treated as a link by markdown processors. (But either tC has a very accepting markdown processor if they use a library one, or else the current tC code actively deletes or ignores the space -- I don't know which. The priority to give an error will always be a matter of opinion, and that opinion will change as the code in our tools changes. I'm not sure that it will be completely practical for the CV package to adjust priorities up and down as our tools become more/less resilient over time? But I can certainly change the priority of this one down if requested because all our tools handle the faulty links.)

**Comment by elsylambert** [comment]
@birchamp As per Robert's comment above, the Priority of this error is lowered to 648 in the latest develop translationCore Create - v1.4.0-rc.2 build 96-14c4cc5 as in the screenshot:
![Screen Shot 2021-11-24 at 10.30.09 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/02475fa0-c660-44a1-9d2b-7ddae15ca88e)
Is that okay?

**Comment by birchamp** [comment]
@elsylambert this is fine.
