### ISSUE TITLE
 SPIKE [8]: Parallel scripture viewer needs to handle reference ranges in the Reference field of the current record

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#718]
What impact does a verse range in the TSV Reference column have on the application?

A TSV record can refer to a reference range (multiple verses). We need to come up with a solution that will show all the verses in the range. The preferred solution will work for both tC Create and gatewayEdit.

Here's a mockup in gatewayEdit:
![CleanShot 2022-08-04 at 09.44.04.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/c1d603c7-5f8d-4706-9639-09a95bb4ca4d)

**Comment by BincyJ** [comment]
Blocked by Catalog Next RCL

**Comment by birchamp** [comment]
All the verses included in the reference range should be displayed as. a single check.
So 1:21-2:3, 22 means the scripture pane would display
v. 1:21
v 2:1
v 2:2
v 2:3
v 2:22

**Comment by PhotoNomad0** [comment]
In searching for a common solution, I found that for rendering:
- TCC uses _scripture-resource-rcl_ ParallelScripture => ScriptureTable => Row => TableRow => TableCell => Verse => VerseObjects
- GWE uses single-scripture-rcl ScriptureCard => ScripturePane => _scripture-resource-rcl_ => VerseObjects

so the overlap is in VerseObjects.

Also for highlighting the words, both apps use SelectionsContextProvider and _scripture-resource-rcl_ accesses this through `useContext(SelectionsContext)`

**Comment by PhotoNomad0** [comment]
Also the Reference Range Library is implemented here: https://github.com/unfoldingWord/tc-create-app/issues/1272

**Comment by birchamp** [comment]
Options:
- modifying VerseObjects and scripture-resource-rcl is one option.  
- replace the parallel scripture with a table that uses single scripture card from gE, and add reference ranges to it.
- anything else you come up with.

**Comment by superdav42** [comment]
I just investigated the feasibility of this:

> * replace the parallel scripture with a table that uses single scripture card from gE, and add reference ranges to it.

I made of [PoC](https://github.com/unfoldingWord/tc-create-app/compare/feature-718-scripture-card-poc#diff-ecd831b73f2e64249ab9d89da64edff39a2f45f7db17dde69ab1c6821aa8e2ffR79-R115) of doing this. 
Here's how it looks:
![image](https://user-images.githubusercontent.com/1534605/184037927-78d8e9ea-1869-477c-b064-1ca63fb700da.png)

Code actually was rather complex. The scripture card is very much tied to how gateway-edit is built. The style could be tweaked so they are side-by-side and better match how ParallelScriptures work but this work be more work. Resource object are similar but different enough that they do not work without much tweaking and basically re-writing how tc-create is built right now. I recommend NOT trying to use ScriptureCards in TC-Create.

I suggest it would be much less effort to update ParallelScripture component to support verse ranges. I made [a PoC](https://github.com/unfoldingWord/scripture-resources-rcl/compare/issue-718-multiple-verses-poc#diff-c1faab52ba95b42d61f950c2425511aed783abe1093a3b2f08f483dadf427999R118) which does this. It is much less work and required only changing a few lines of code. Here's how it looks:
![image](https://user-images.githubusercontent.com/1534605/184038323-93d26bd8-7b0f-4264-a68e-db2efad6dcc8.png)
Of course it's just a PoC because things are hard coded but I think it's enough to say we should go this route of using ParallelScripture component and updating it to properly handle verse ranges.

So I believe the best strategy is to add verse range support to both components ParallelScripture and ScriptureCard which may seem like duplicated work but it the end should save the extra effort of making ScriptureCard work with tc-create

**Comment by larsgson** [comment]
I have created a custom hook "**useBcvQuery**" in the RCL component scripture-resources-rcl. This hook retrieves multiple verses' resources from DCS through a structured query. 

The query structure makes it easy to retrieve information from any multiple verses and to specify any expected format _(currently the implementation is limited to a single book only and only "verseObjects" format, but if needed then this could be expanded in the future)_.

The result is in a tree structure - making it is easy to transform to any other format as needed.

I have included a working demo in the styleguidist under the menu "ResourceContextProvider", like here:
![VerseRange-useBcvQuery](https://user-images.githubusercontent.com/4819617/184385378-4d191dd4-2474-4889-93b4-536ea2acd8d4.png)

**Comment by larsgson** [comment]
I have decided to not yet create any PR, nor publish any "alpha" to NPM, since @superdav42 is still working on the same issue and in this very RCL.
I will now start to adapt the code in ScripturePane and ScriptureCard in single-scripture-rcl as a demo of how to use this hook for having verse ranges there.
