### ISSUE TITLE
On-open validator reports errors on ru tN tsv files

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#737]
v1.2.0-rc.2 build 28-4717783

file here: [https://app.zenhub.com/files/191973535/1f76977a-78ed-4a04-9d49-822cf417fbec/download](https://app.zenhub.com/files/191973535/1f76977a-78ed-4a04-9d49-822cf417fbec/download)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/51025293-5564-46b4-8094-2019b0f42836)

Log in and select the Russian tN project for Titus.
Note that the on-open validator reports an invalid header, and that line 199 only contains 7 columns. Upon examining the file, I don't see any problem with the header, and all rows have 8 tabs in them.

**Comment by cckozie** [comment]
Tested in tCC tN Test On-Open Validator

**Comment by mandolyte** [comment]
@cckozie @birchamp 

It isn't obvious what the issue is with the header. But here is the issue with line 199:
- in the past, we've had issues with a blank line at the end of the file
- thus in some cases we trim whitespace off the end of the file to prevent this from causing issues
- in the this issue, the file has empty columns on the last row.
- which means it ends with a bunch of tab characters... which are "whitespace"... which are then trimmed
- which means it has fewer columns than it is supposed to
- and then the validator reports it

This could be patched pretty easily. However, at this point there are several problems with how we parse TSV files and I propose instead that we take a bit more time to create an official TSV parser for us to use across our tools.

In particular, I propose a lax implementation of the spec that Robert Hunt calls out [here](https://en.wikipedia.org/wiki/Tab-separated_values#Conventions_for_lossless_conversion_to_TSV).

I say "lax" because, we could easily fill out extra columns if they are missing from a row and attempt to fix rows that have too many columns (there are one or two things that can be attempted, but some cases may not be fixable).

**Comment by birchamp** [comment]
@mandolyte are you talking about a RCL that's simply a TSV parser? Or just modifications to how Datatable-translatable parses?

**Comment by mandolyte** [comment]
@birchamp Technically, it would not be an RCL since it would be pure code, no UI. So it would be like our USFM.js or uw-content-validation package.

Over time everything that needs to parse TSV in the spec compliant way could use instead of writing it ourselves each time. I can find several places in the codebase today where TSV is parsed, sometimes with slight differences. But none conform to what Robert wants use to use (he points us to https://en.wikipedia.org/wiki/Tab-separated_values)

**Comment by mandolyte** [comment]
I should note that this could be included in the gitea-react-toolkit (it will find a lot of use there anyway).

**Comment by birchamp** [comment]
@klappy thoughts on this idea?

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.2.0-rc.3 build 28-c60492b. Able to open Russian tN for Titus and 3Jn and seeing Russian text on the target side. For other books shows english on the target side, for which the Russian does not exists. works as expected.
Tested with multiple sessions, too. Looks good.

**Comment by klappy** [comment]
I like the idea of having a uW tsv parser that is used across RCLs and apps. I would like us to consider the separation of concerns and ensure that what ever RCL the parser is included in is considered as to not bloat the apps with unnecessary dependencies.

**Comment by cckozie** [comment]
The error reported has been fixed in v1.2.0-rc.3 build 28-c60492b, and the on-open validator no longer hangs when opening the Russian projects.
However, the validator is now incorrectly reporting missing tab characters. I wrote this up in #808.

**Comment by cckozie** [comment]
In v1.2.0 build 41-eb23e86 I am again seeing the on-open validator report a bad header on Russian tN files even though the header is the same as for the equivalent English file. I'm seeing this on multiple books, example here is for Titus.
[ru_tn_57-TIT-A.tsv.zip](https://github.com/unfoldingWord/tc-create-app/files/6417610/ru_tn_57-TIT-A.tsv.zip)

![image](https://user-images.githubusercontent.com/8171759/116929846-998eba00-ac24-11eb-8688-81c5d17fde61.png)

---Russian:---
![image](https://user-images.githubusercontent.com/8171759/116930603-9516d100-ac25-11eb-9c23-c8ac7a1ca90f.png)

**Comment by mandolyte** [comment]
@cckozie The file you provided uses Windows line endings; in other words each line ends with a Carriage Return (CR) and a Line Feed (LF). On *nix:
```sh
$ head -1 ru_tn_57-TIT-A.tsv| cat -vt
Book^IChapter^IVerse^IID^ISupportReference^IOrigQuote^IOccurrence^IGLQuote^IOccurrenceNote^M
$ 
```
The "^I" characters are tabs; the last character "^M" is a CR. This CR is present in translate_test/ru_tn, which I think is where this is coming from, right?

In the master branch (ru_gl/ru_tn), that character is not there:
```sh
$ head -1 en_tn_57-TIT.tsv | cat -vt
Book^IChapter^IVerse^IID^ISupportReference^IOrigQuote^IOccurrence^IGLQuote^IOccurrenceNote
$
```
Could you refresh your branch and retest?

NOTE: tc-create will not put the CRLF at the end of the lines. This is a Windows/DOS convention. I believe that Github will convert Windows files automatically to just have LF as the line ending. But I'm sure it can be overridden, but I don't know how. Nor do I know if Gitea behaves the same.

**Comment by cckozie** [comment]
@mandolyte - I don't doubt what you've written in the comment above, but this issue passed back on v1.2.0-rc.3 build 28-c60492b and I've done nothing to change the file. Also, I downloaded the raw Titus files from both the ru and en repos. The headers look identical in TextWrangler, and the en project loads fine.
![image](https://user-images.githubusercontent.com/8171759/116956831-e772e480-ac5b-11eb-90bb-4dbeec671d96.png)

**Comment by ancientTexts-net** [comment]
@cckozie @mandolyte 

I am looking into this issue too.  Could I have a link to the `qa` repo for this file please?

Thanks

**Comment by ancientTexts-net** [comment]
@cckozie is it possible that when the QA server was refreshed, something "bad" happened to the file?

**Comment by cckozie** [comment]
@ancientTexts-net The Titus file is here: https://qa.door43.org/translate_test/ru_tn/src/branch/tc01-tc-create-1/en_tn_57-TIT.tsv
I suppose anything is possible :). I'm seeing the same problem in Ruth and 3 John, but not in a couple others I've tested.

**Comment by ancientTexts-net** [comment]
@cckozie @mandolyte 

Thanks Koz.

Cecil, not sure it has to do with the FILE CONTENTS.  I used git to put a "good" English version in my translate_test branch:
https://qa.door43.org/translate_test/ru_tn/src/branch/ZachPennington-tc-create-1/en_tn_57-TIT.tsv

I still get the error when I try to open the file... strange?

**Comment by ancientTexts-net** [comment]
Ready to test again please

https://develop--tc-create-app.netlify.app/
v1.2.0 build 42-1c85d30

**Comment by cckozie** [comment]
v1.2.0 build 42-1c85d30
I am no longer seeing the header error message on the files where the header was terminated by a carriage return.

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0 build 42-1c85d30. Looks good. Not seeing header issues in Russian tN files.
