### ISSUE TITLE
Add on open validation for TWL

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#787]
When the user opens the TWL do initial validation like TN TSV does currently.

**Comment by ancientTexts-net** [comment]
@mandolyte 

Added some comments in Reviewable:

https://github.com/unfoldingWord/tc-create-app/pull/824

**Comment by ancientTexts-net** [comment]
ready for testing

https://develop--tc-create-app.netlify.app/
translationCore Create - `v1.2.0-rc.4 build 33-43fd9f5`

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0-rc.4 build 33-43fd9f5.
On-open validator reports error if the file has a bad header or a missing column for each row. Works as expected.

**Comment by cckozie** [comment]
I'm seeing 2 problems in v1.2.0-rc.5 build 34-ab649d5
![image](https://user-images.githubusercontent.com/8171759/116126214-ff5ecd00-a68b-11eb-8578-1d5bbad82665.png)

1. The validator reports that the header must have 7 or 9 columns while reporting that it expects other rows to have 5 columns. tWL projects actually should have 6 columns.
2. The validator does not report a problem when there are more than 5 tabs.

**Comment by ancientTexts-net** [comment]
works if I corrupt a row (below)

but get grey (crash) screen if I corrupt the header by adding an extra column

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/22c6c5df-1da3-4190-8d7b-53095e4348b4)

**Comment by ancientTexts-net** [comment]
works now 
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/1e1dbdcd-c961-4637-ac0b-4516e5fa555c)

**Comment by ancientTexts-net** [comment]
https://develop--tc-create-app.netlify.app/
v1.2.0-rc.6 build 37-1f07640

**Comment by cckozie** [comment]
v1.2.0-rc.6 build 37-1f07640
It is better, but there still is a problem.
When there is a missing tab in the header row, this message is displayed:
![image](https://user-images.githubusercontent.com/8171759/116478237-62df2b00-a843-11eb-8c9a-bdb581d4d870.png)

When the link is clicked, this is what the user sees. This will be confusing because it looks like the header is good.
![image](https://user-images.githubusercontent.com/8171759/116478294-78eceb80-a843-11eb-8cc6-fecf5cd1b105.png)

The message should indicate that there are 4 tabs when there should be 5.

**Comment by ancientTexts-net** [comment]
`v1.2.0-rc.7 build 39-98443c4`

**Comment by ancientTexts-net** [comment]
@cckozie @mandolyte 
v1.2.0-rc.7 build 39-98443c4

**Comment by cckozie** [comment]
Looks good in v1.2.0-rc.7 build 39-98443c4

**Comment by elsylambert** [comment]
Looks good in  v1.2.0-rc.8 build 40-f9678ab.
