### ISSUE TITLE
Allow users to indent bullet lists within a numbered list

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#871]
Issue:
---
Users should be able to indent a bulleted list (unordered list) within a numbered (ordered) list.  Markdown specifies that 2 spaces beyond the previous level will indent the list https://spec.commonmark.org/0.28/#list-items. **Note** that  typing more than 4 spaces beyond the initial mark of the previous level will create a code block.

**The proposed solution is to disable preview mode editing.**

DoD:
---
typing 2 spaces beyond the initiating marker of the previous level will indent the unordered list.  

Details:
---
* v 1.2.0 allows for indented bulleted lists within a numbered list using 4 spaces before the \* 
* v 1.2.1 ignores the 4 spaces, creates a separate bulleted list, and restarts the numbering. 
* This appears to be a regression due to the changes in #613
**NOTE**: 5 spaces will indent the nested list in v1.2.1

v1.2.0
---
<img src="https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/1f10186c-9f64-44ad-9d7f-be743149d5c9" width ="400">

v 1.2.1 
---
<img src="https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/e3fe6fb2-7def-4e12-bbd8-cf4a191ce515" width ="700">

**Comment by birchamp** [comment]
@cckozie can you confirm that you're seeing this?

**Comment by cckozie** [comment]
test

**Comment by birchamp** [comment]
So does this fail #613?

**Comment by ancientTexts-net** [comment]
one suggestion:

Currently: We DIVIDE BLOCKS based on the markdown content
- this behavior ends up breaking the MD rendering rules (e.g., nested lists, sequential ordered lists, etc)
- since each block is rendered as a separate document, without the context of the larger file

Suggested: DIVIDE BLOCKS after rendering.  That is, divide based on HTML:
- possibly divide on the <p> paragraph tag? other tags?
- this means the whole markdown document is rendered as a whole

**Comment by ancientTexts-net** [comment]
@birchamp  provided some videos comparing ZULIP markdown preview

Birch — 10/29/2021
We we need to meet with the  Content team to confirm before we do that.
I can't get it to behave is that because the source side is restricting it?

Birch — 10/29/2021
check this video of what I'm seeing. https://drive.google.com/file/d/19FQa6JCGkoHJ1zovA7nbRXcxq4LRpsKA/view?usp=sharing


Birch — 10/29/2021
I'm wondering what would happen if we ignored the whitespace like zulip does - https://drive.google.com/file/d/1iG9P55GQWI8AdFur5RvNEkblTcQ8Hlad/view?usp=sharing

**Comment by ancientTexts-net** [comment]
@jincypjose 

the problem here is:
- yes, zulip "IGNORES" MD paragraphs in PREVIEW mode
- but notice that zulip "PRESERVES" the users original markdown (SINCE THEY CAN'T EDIT IN PREVIEW MODE 🤯🤯)
- BUT our current implementations of "EDIT MODE" (tC Create) have TWO WAY conversion ( HTML <--> MD)
- THEN in our apps, we would be altering the user data (SAVED back to DCS)

that's OK we just want to discuss first

**Comment by ancientTexts-net** [comment]
the way we choose to render the HTML
--> will change the content of the MARKDOWN

**Comment by ancientTexts-net** [comment]
@birchamp just confirming we are moving forward testing this approach:
- remove the extra invalid linebreaks (INVALID markdown)
- NOTE: this edit will be reflected in the users' data file

**Comment by ancientTexts-net** [comment]
thanks

**Comment by birchamp** [comment]
@birchamp discuss with stakeholders disabling preview editing. Discuss normalizing all line breaks in MD.

**Comment by birchamp** [comment]
@jincypjose The stakeholders have said that we can turn off editing in Preview mode.

**Comment by birchamp** [comment]
@elsylambert can you retest this now that Preview mode editing has been turned off?
